---

- name: Create {{ splunk_home }} dir
  file:
    path: "{{ splunk_home }}"
    state: directory
    mode: '0755'  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: Uploading ./files/{{ splunk_tgz }} (local) to /home/{{ os_user }}/ (remote)
  copy:
    src: "files/{{ splunk_tgz }}"
    dest: /home/{{ os_user }}
    mode: '0640'
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes
  when: splunk_tgz_downloaded_flag.stat.exists == False and not download_tgz_from_splunk_servers 

- name: Check if Splunk has ever been run via initd
  stat: 
    path: /etc/init.d/splunk
  register: initd_run_flag

- name: Check if Splunk has ever been run via systemd
  stat: 
    path: /etc/systemd/system/Splunkd.service
  register: systemd_run_flag

- name: -initd- Stop Splunk pre-upgrade
  command: "{{ splunk_home }}/bin/splunk stop"
  become: yes  
  when: initd_run_flag.stat.exists == True

- name: -systemd- Stop Splunk pre-upgrade
  systemd:
    name: Splunkd
    state: stopped
  become: yes
  when: systemd_run_flag.stat.exists == True

- name: Extract {{ splunk_tgz }} over {{ splunk_home }} to upgrade
  unarchive:
    src: /home/{{ os_user }}/{{ splunk_tgz }}
    dest: "{{ splunk_home }}/.."
    remote_src: yes
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: -systemd- For initd -> systemd upgrades remove initd script
  command: "{{ splunk_home }}/bin/splunk disable boot-start --no-prompt --answer-yes --accept-license"
  become: yes
  when: 
    - install_method == "systemd"

- name: -systemd & Splunk 7.3- For initd -> systemd upgrade rebuild systemd script
  command: "{{ splunk_home }}/bin/splunk enable boot-start -systemd-managed 1 -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes
  when: 
    - install_method == "systemd"  
    - splunk_version is version('7.3', '>=')   


- name: -systemd- Start Splunk for the first time post upgrade
  command: "systemctl start Splunkd"
  become: yes
  when: 
    - install_method == "systemd"
