---
- name: Create Mgmt SVM
  na_ontap_svm:
      state: "{{ state }}"
      name: "{{ mgmt_svm }}"
      root_volume: "{{ mgmt_rootvolname }}"
      root_volume_aggregate: "{{ mgmt_rootvolaggr }}"
      root_volume_security_style: "{{ mgmt_rootvolsecurity }}"
      aggr_list: "{{ mgmt_allowedaggrs }}"
      allowed_protocols: "{{ mgmt_allowedprotocols }}"
      <<: login


- name: Create cifs_server
  na_ontap_cifs_server:
    state: "{{ state }}"
    name: "{{ cifs_servername }}"
    vserver: "{{ mgmt_svm }}"
    service_state: started
    domain: "{{ ad_domain }}"
    admin_user_name: "{{ ad_user }}"
    admin_password: "{{ ad_psw }}"
    ou: "{{ ou }}"
    <<: login

- name: Create Snapshot policy
  na_ontap_snapshot_policy:
    state: "{{ state }}"
    name: "{{ snap_policy_name }}"
    schedule: "{{ jobname }}"
    prefix: "{{ jobname }}"
    count: 4
    enabled: True
    <<: login


#Create AD authentication
- name: Create a Domain Tunnel
  na_ontap_command:
    command: ['security', 'login', 'domain-tunnel', 'create', '-vserver', "{{ mgmt_svm }}"]
    privilege: admin
    <<: login

- name: Create AD Group
  na_ontap_user:
    state: "{{ state }}"
    name: "{{ ad_group }}"
    applications: ssh,console,http,ontapi
    authentication_method: domain
    lock_user: false
    role_name: vsadmin
    vserver: "{{ clustername }}"
    <<: login


