---
- hosts: localhost
  vars_files:
    - passwd
  vars:
    netapp_hostname: storageadsasd
    netapp_username:
    netapp_password:
    svm_name: namn
    snapshot_policy: 
    allowed_protocols: nfs, cifs
  tasks:
    - name: Create SVM Ansible
      na_ontap_svm:
        state: present
        name: "{{ svm_name }}"
        root_volume: "{{ svm_name }}_rootvol"
        root_volume_aggregate: aggr1
        root_volume_security_style: unix
        validate_certs: no
        snapshot_policy: "{{  snapshot_policy }}"
        https: true
        allowed_protocols:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"

    - name: Display encryoted variable
      debug: 
        msg: "{{ password }}"
        --- https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/