---

- name: Add "{{ os_group }}" group
  group:
    name: "{{ os_group }}"
    state: present  
  become: yes  

- name: Add "{{ os_user }}" user with the home dir /home/{{ os_user }}/
  user:
    name: "{{ os_user }}"
    group: "{{ os_group }}"
    home: /home/{{ os_user }}/
    shell: /bin/bash
    comment: Splunk User
  become: yes


- name: ulimits - Set /etc/security/limits.conf for "{{ os_user }}" user
  template:
    src: limits.conf.j2
    dest: "/etc/security/limits.conf"
  become: yes
  when: ulimits == true

- name: Create {{ splunk_home }} dir
  file:
    path: "{{ splunk_home }}"
    state: directory
    mode: '0755'  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes